### ISSUE TITLE
Loading spinning wheel of some kind

### ISSUE THREAD

**Issue by nickerso** [AnatomicMaps/flatmap-dashboard#1]
Would be useful to have some kind of indication of content loading. e.g., the flatmap page looks empty until it suddenly populates with a big table of maps.

(not at all a priority, just wanted to get the first issue in!)

**Comment by dbrnz** [comment]
100% -- I'm playing with this ATM!

**Comment by dbrnz** [comment]
Implemented as part of commit b140b7d.
